name: test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install nuget
      uses: nuget/setup-node@v3
      with:
          node-version: 18
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: build
      run: npm run build