name: test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@3
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: build
      run: npm run build